---
- name: install package
  portage: package=net-misc/memcached
  tags: packages

- name: configure memcached
  template: >
    src=memcached.j2
    dest=/etc/conf.d/memcached
    owner=root group=root mode=0644
  tags: config

- name: enable and start memcached
  service: >
    name=memcached
    enabled=yes
    state=started
  tags: services
